from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import os


class PDFReport:
    def __init__(self, output_folder="reports"):
        self.output_folder = output_folder

        if not os.path.exists(output_folder):
            os.makedirs(output_folder)

    def generate_report(
        self,
        filename,
        temperature,
        humidity,
        leaf_color,
        leaf_spot,
        leaf_curl,
        model_name,
        predicted_disease
    ):
        """
        Generate prediction PDF report.
        """

        pdf_path = os.path.join(
            self.output_folder,
            filename
        )

        pdf = canvas.Canvas(pdf_path, pagesize=letter)

        width, height = letter

        y = height - 50

        pdf.setFont("Helvetica-Bold", 18)
        pdf.drawString(180, y, "HarvestVision Report")

        y -= 40

        pdf.setFont("Helvetica", 12)

        pdf.drawString(50, y, f"Temperature : {temperature}")
        y -= 25

        pdf.drawString(50, y, f"Humidity : {humidity}")
        y -= 25

        pdf.drawString(50, y, f"Leaf Color : {leaf_color}")
        y -= 25

        pdf.drawString(50, y, f"Leaf Spot : {leaf_spot}")
        y -= 25

        pdf.drawString(50, y, f"Leaf Curl : {leaf_curl}")
        y -= 25

        pdf.drawString(50, y, f"Prediction Model : {model_name}")
        y -= 25

        pdf.drawString(
            50,
            y,
            f"Predicted Disease : {predicted_disease}"
        )

        y -= 50

        pdf.setFont("Helvetica-Bold", 14)
        pdf.drawString(
            50,
            y,
            "Generated by HarvestVision"
        )

        pdf.save()

        return pdf_path